name: "Security Vulnerability Report"
description: ONLY USE FOR INTERNAL TRACKING. Do NOT use this for public disclosure.
title: "[SECURITY] Brief Summary of Vulnerability"
labels: ["security", "critical-priority", "triage"]
assignees: [Neil-urk12,ChristianAlicaba2002] 

body:
  - type: markdown
    attributes:
      value: |
        # 🚨 WARNING: DO NOT DISCLOSE VULNERABILITIES PUBLICLY 🚨
        
        If you are an external user, **STOP**, Please contact the project owners privately.
        
        This public issue form is for **internal-only** tracking purposes after a private report has been filed.
        
  - type: textarea
    id: vulnerability-summary
    attributes:
      label: "📝 Summary"
      description: A concise description of the vulnerability (e.g., Cross-Site Scripting in X component).
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🔬 Steps to Reproduce"
      description: |
        Detail the steps needed to reproduce the exploit. Provide a minimal example, if possible.
        
        1. [Step 1]
        2. [Step 2]
        3. [etc.]
        
        *Note: If you are an external reporter and this is sensitive, you should be using the private reporting form.*
    validations:
      required: true

  - type: textarea
    id: affected-component
    attributes:
      label: "📦 Affected Component & Version"
      description: Which part of the codebase/system is vulnerable, and what is the affected version or commit SHA?
      placeholder: "e.g., 'API endpoint /users/v1, version 2.5.0' or 'Commit SHA: abcdef123456'"
    validations:
      required: true

  - type: dropdown
    id: cvss-severity
    attributes:
      label: "Severity (Initial Assessment)"
      description: Your preliminary assessment of the impact.
      options:
        - Critical (Remote Code Execution, full database compromise)
        - High (Privilege escalation, account takeover)
        - Medium (Sensitive data disclosure, limited XSS)
        - Low (Minor issue, denial of service with no data loss)
    validations:
      required: true
      
  - type: checkboxes
    id: policy-acknowledgement
    attributes:
      label: "Policy Acknowledgment"
      options:
        - label: "I confirm that I have reported this vulnerability through the private channel (e.g., GitHub Advisory, Email, etc.) or am an internal security team member using this for tracking."
          required: true

